<LoginScreen>:
    FloatLayout:
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1  # Black background
            Rectangle:
                pos: self.pos
                size: self.size

        Image:
            source: 'keycloak_logo.png'
            size_hint: (None, None)
            size: (90, 90)  # Reduced logo size
            pos_hint: {'center_x': 0.5, 'top': 0.98}

        Label:
            text: "Log In"
            font_size: "24sp"  # Bold and larger title
            bold: True
            size_hint: (None, None)
            height: 50
            pos_hint: {'center_x': 0.5, 'top': 0.78}
            color: (0, 0, 0, 1)

        
        BoxLayout:
            orientation: 'vertical'
            size_hint: (0.8, None)
            height: 250
            pos_hint: {'center_x': 0.5, 'center_y': 0.45}
            spacing: 5

            Widget:
                size_hint_y: None
                height: 90  # Điều chỉnh giá trị này để thay đổi khoảng cách

            # Username Section
            BoxLayout:
                orientation: 'vertical'
                spacing: 5

                Label:
                    text: "Username"
                    font_size: "14sp"
                    color: (0, 0, 0, 1)
                    halign: 'left'
                    valign: 'middle'
                    size_hint_y: None
                    height: 20
                    text_size: self.size  # Aligns text within bounds
                   

                TextInput:
                    id: username
                    hint_text: "Enter your username"
                    multiline: False
                    size_hint_y: None
                    height: 40

                Widget:
                    size_hint_y: None
                    height: 20  # Điều chỉnh giá trị này để thay đổi khoảng cách
          

            # Password Section
            BoxLayout:
                orientation: 'vertical'
                spacing: 5

            
                Label:
                    text: "Password"
                    font_size: "14sp"
                    halign: 'left'
                    valign: 'middle'
                    size_hint_y: None
                    height: 20
                    text_size: self.size  # Aligns text within bounds
                    color: (0, 0, 0, 1)

                TextInput:
                    id: password
                    hint_text: "Enter your password"
                    password: True
                    multiline: False
                    size_hint_y: None
                    height: 40

              # Spacer to increase space above the button
            Widget:
                size_hint_y: None
                height: 5  # Increased space between Password and Button

            # Login Button
            Button:
                text: "Log In"
                background_color: (0.0, 0.3, 0.7, 1)  # Dark blue button
                color: (1, 1, 1, 1)
                size_hint_y: None
                height: 45
                on_release: root.validate_user()
                
